// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	interview_center "Ai-HireSphere/application/interview-center/protocol/api/internal/handler/interview_center"
	"Ai-HireSphere/application/interview-center/protocol/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: interview_center.ResumeAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: interview_center.ChatHandler(serverCtx),
			},
		},
	)
}
