// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	base "Ai-HireSphere/application/user-center/interfaces/api/internal/handler/base"
	user "Ai-HireSphere/application/user-center/interfaces/api/internal/handler/user"
	"Ai-HireSphere/application/user-center/interfaces/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发送验证码
				Method:  http.MethodPost,
				Path:    "/captcha/send",
				Handler: base.CaptchaSendHandler(serverCtx),
			},
			{
				// 验证验证码
				Method:  http.MethodPost,
				Path:    "/captcha/verify",
				Handler: base.CaptchaVerifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/base"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/data",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)
}
