// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UploadResumeReq struct {
	Resume []byte `form:"resume"`
	Name   string `form:"name"`
}

type UploadResumeResp struct {
	Address string `json:"address"`
}
