FROM 8.134.142.155:8888/ops/golang:1.23-builder AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn,https://goproxy.io,https://mirrors.aliyun.com/goproxy/,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories


WORKDIR /build

ADD go.mod .
ADD go.sum .
RUN for i in $(seq 1 3); do go mod download && break || sleep 5; done
COPY . .
RUN go build -ldflags="-s -w" -o /app/interview-api application/interview/interfaces/api/interview.go


FROM registry.cn-guangzhou.aliyuncs.com/dbinggo-docker/alpine:latest

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ=Asia/Shanghai

WORKDIR /app
COPY --from=builder /app/interview-api /app/interview-api

CMD ["./interview-api", "-f", "etc/interview-api.yaml"]
