FROM registry.cn-guangzhou.aliyuncs.com/dbinggo-docker/golang:1.23-alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update --no-cache && apk add --no-cache tzdata



WORKDIR /cache

ADD go.mod .
ADD go.sum .
RUN go mod download

COPY . .
RUN go build -ldflags="-s -w" -o /cache/user-api application/user-center/interfaces/api/user.go
RUN go build -ldflags="-s -w" -o /cache/interview-api application/interview/interfaces/api/interview.go
RUN go build -ldflags="-s -w" -o /cache/interview-rpc application/interview/interfaces/rpc/interview.go
RUN go build -ldflags="-s -w" -o /cache/user-rpc application/user-center/interfaces/rpc/user.go

RUN rm -rf /cache