// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaSendReq struct {
	Way    string `json:"way"`
	Target string `json:"target"`
}

type CaptchaVerifyReq struct {
	Way    string `json:"way"`
	Target string `json:"target"`
	Code   string `json:"code"`
}

type LoginReq struct {
	Way  string `json:"way"`
	Data string `json:"data"`
	Code string `json:"code"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}

type RegisterReq struct {
	Way  string `json:"way"`
	Data string `json:"data"`
	Code string `json:"code"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}
