// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Way  string `json:"way"`
	Data string `json:"data"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}
