// Code generated by goctl. DO NOT EDIT.
package types

type ChatRequest struct {
	SessionID int64  `json:"session_id,optional"`
	Message   string `json:"message"`
	IsNew     bool   `json:"is_new"`
}

type Resume struct {
	UserID int64  `json:"user_id" form:"user_id"`
	Name   string `json:"name" form:"name"`
}

type ResumeAddRequest struct {
	Resume
}

type ResumeAddResponse struct {
	ID int64 `json:"id"`
}
